### ISSUE TITLE
你好，项目clone下来运行之后有一点问题想咨询一下

### ISSUE THREAD

**Issue by tomixiaohei** [saucxs/weekly#2]
![image](https://user-images.githubusercontent.com/24702137/56710289-ee56ea80-6757-11e9-9ca5-930c65093d81.png)

显示
Error: add data is empty

**Comment by tomixiaohei** [comment]
![image](https://user-images.githubusercontent.com/24702137/56710166-61139600-6757-11e9-822b-9936e1899e2b.png)

> 显示
> Error: add data is empty

**Comment by tomixiaohei** [comment]
> ![image](https://user-images.githubusercontent.com/24702137/56710103-17c34680-6757-11e9-887c-9d712e74f660.png)
> 
> 显示
> Error: add data is empty

**Comment by tomixiaohei** [comment]
登录不管输入什么都显示服务开小差，是我的设置有问题么？

**Comment by saucxs** [comment]
你定位一下具体出问题的地方，这样我看不出来问题，或者你把出错的node那块日志粘贴一下

**Comment by tomixiaohei** [comment]
![image](https://user-images.githubusercontent.com/24702137/56713962-e1d98e80-6765-11e9-8ca6-2f3237a57838.png)

**Comment by tomixiaohei** [comment]
就是这样啦~

**Comment by saucxs** [comment]
这个已经写了error add data is empty，错误在这个地方。你数据库配置，redis配置都ok了吗？这个如果上手困难的话，可以看这个项目[https://github.com/saucxs/structure-admin](https://github.com/saucxs/structure-admin)这个主要是给出了数据库文件，具体操作详细阅读readme。

**Comment by tomixiaohei** [comment]
嗯，好的，谢谢大佬
